begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

#APP_RAKEFILE = File.expand_path("../test/dummy/Rakefile", __FILE__)
#load 'rails/tasks/engine.rake'
#load 'rails/tasks/statistics.rake'

Bundler::GemHelper.install_tasks

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = false
  t.warning = false
end


task default: :test

require 'push_type/testing/common_rake'

desc "Generates a dummy app for testing"
task :test_app do
  ENV['RAILS_ENV'] = 'test'
  Rake::Task['common:test_app'].invoke 'push_type_auth', File.dirname(__FILE__)
end