json.id           node.id
json.type         node.type
json.is_exposed   node.exposed?
json.parent_id    node.parent_id
json.title        node.title
json.slug         node.slug
json.permalink    node_url(node)
json.created_at   node.created_at
json.updated_at   node.updated_at
json.published_at node.published_at
json.published_to node.published_to
json.children     node.children.count
json.is_trashed   node.trashed?
